# Generated by Django 3.0.8 on 2020-08-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainc', models.CharField(max_length=500)),
                ('domain', models.IntegerField(null=True)),
                ('areac', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=500)),
                ('elemc', models.IntegerField(null=True)),
                ('elem', models.CharField(max_length=500)),
                ('itemc', models.IntegerField(null=True)),
                ('item', models.CharField(max_length=500)),
                ('yearc', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=500)),
                ('value', models.IntegerField(null=True)),
                ('Flag', models.CharField(max_length=500)),
                ('Flagd', models.CharField(max_length=500)),
            ],
        ),
    ]
