# Generated by Django 3.0.8 on 2020-08-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_crop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop',
            table='crop',
        ),
    ]
